spring.application.name=demo

# JPA / HIBERNATE
# Mostra o SQL gerado no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#acessar em localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurações da Twilio
twilio.account.sid=${TWILIO_ACCOUNT_SID}
twilio.auth.token=${TWILIO_AUTH_TOKEN}
twilio.whatsapp-from=whatsapp:+14155238886

spring.datasource.url=jdbc:postgresql://localhost:5432/whatsapp_assistant
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=whatsapp_assistant
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
